FROM docker.io/node:17-alpine as builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM docker.io/nginx:alpine as runtime
WORKDIR /usr/share/nginx/html
COPY --from=builder /usr/src/app/public/ .

# This **WAS** added in previously, but should now be mounted in.
# COPY default.conf /etc/nginx/conf.d/default.conf