---
## Is Bonnie Recording
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "is-bonnie-recording"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/danmanners/IsBonnieRecording"
    path: manifests
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: isbonrecording
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
