---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: recording-cert
spec:
  commonName: isbonnierecording.danmanners.com
  secretName: recording-cert
  dnsNames:
    - isbonnierecording.danmanners.com
    - shutthefuckup.danmanners.com
    - recording.danmanners.com

  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
