---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: isbonnierecording
  name: is-bon-recording
  namespace: default
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  selector:
    matchLabels:
      run: isbonnierecording
  template:
    metadata:
      labels:
        run: isbonnierecording
    spec:
      nodeSelector:
        feature.node.kubernetes.io/custom-blink1: 'true'
      containers:
      - image: ghcr.io/danmanners/isbonrecording-frontend:v0.1.1
        imagePullPolicy: IfNotPresent
        name: frontend
        resources:
          limits:
            cpu: "1"
            memory: 160Mi
          requests:
            cpu: 500m
            memory: 96Mi
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
        ports:
        - containerPort: 5000
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: ghcr.io/danmanners/isbonrecording-backend:v0.1.1
        imagePullPolicy: IfNotPresent
        name: backend
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "1"
            memory: 160Mi
          requests:
            cpu: 500m
            memory: 96Mi
        ports:
        - containerPort: 9080
          protocol: TCP
        volumeMounts:
          - mountPath: /dev/hidraw0
            name: ttyblink
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: ttyblink
          hostPath:
            path: /dev/hidraw0
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
            - key: default.conf
              path: default.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 3
