---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: blink-controller
  name: is-bon-recording
  namespace: default
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  selector:
    matchLabels:
      run: blink-controller
  template:
    metadata:
      labels:
        run: blink-controller
    spec:
      nodeSelector:
        feature.node.kubernetes.io/custom-blink1: 'true'
      containers:
      - image: danielmanners/isbonrecording-frontend:arm64
        imagePullPolicy: Always
        name: frontend
        resources:
          limits:
            cpu: "1"
            memory: 160Mi
          requests:
            cpu: 500m
            memory: 96Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: danielmanners/isbonrecording-backend:arm64
        imagePullPolicy: Always
        name: backend
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "1"
            memory: 160Mi
          requests:
            cpu: 500m
            memory: 96Mi
        volumeMounts:
          - mountPath: /dev/hidraw0
            name: ttyblink
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: ttyblink
          hostPath:
            path: /dev/hidraw0
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 3
