---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: isbonrecording
resources:
  - namespace.yaml
  - certs.yaml
  - deployment.yaml
  - service.yaml
  - traefik.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: nginx-config
    files:
      - ./files/default.conf
