---
apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    run: blink-controller
  name: is-bon-recording
spec:
  containers:
  - image: localhost/ibr-frontend:dev
    name: frontend
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    ports:
    - containerPort: 80
      protocol: TCP
      hostPort: 5000
  - image: localhost/ibr-backend:dev
    name: backend
    securityContext:
      privileged: true
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    ports:
    - containerPort: 9080
      protocol: TCP
      hostPort: 9080
    volumes:
    - name: ttyblink
      hostPath:
        path: /dev/hidraw0
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  securityContext: {}
  terminationGracePeriodSeconds: 3
